#!/usr/bin/env python

SIZE_HEADER = 7
PORT         = 64720 # hex:fcd0

CHAIN_RECALC_INTERVAL = 2016

MAGIC_PING_RETRIES = 5
MAGIC_PING_TIMEOUT = 30

CTYPE_REJECT     = 0
CTYPE_GETHIGHEST = 1
CTYPE_GETCHAIN   = 2
CTYPE_GETTXS     = 3
CTYPE_GETPEERS   = 4
CTYPE_INV        = 5
CTYPE_GETDATA    = 6
CTYPE_BLOCK      = 7
CTYPE_TX         = 8
CTYPE_PEER       = 9
CTYPE_ALERT      = 10
CTYPE_PING       = 11
CTYPE_PONG       = 12

DTYPE_BLOCK = 0
DTYPE_TX    = 1

OTYPE_WARNUSER    = 0 # Display a warning to the user, visible at all times.
OTYPE_FORCEUPDATE = 1 # Do not allow user to do anything until the client is updated.

ERR_BAD_VERSION = 1
ERR_BAD_CTYPE = 2
ERR_BAD_DTYPE = 3
ERR_BAD_ATYPE = 4
ERR_MESSAGE_MALFORMED = 5

ERR_BLOCK_BLACKLISTED = 6
ERR_BLOCK_INVALID     = 7

ERR_TX_INVALID        = 8