#!/usr/bin/env python

import socket
import sys
import atexit

ADDR = "localhost"
PORT = 64720

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
atexit.register(sock.close)

sock.connect((ADDR, PORT))
sock.sendall(b'\xde\xad\xbe\xef')
while True:
    data = sock.recv(1024)
    if data == b"":
        print("Disconnected")
        break
    else:
        print(data)